 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/preferences_users", type: :request do
  # PreferencesUser. As you add validations to PreferencesUser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PreferencesUser.create! valid_attributes
      get preferences_users_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      preferences_user = PreferencesUser.create! valid_attributes
      get preferences_user_url(preferences_user)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_preferences_user_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      preferences_user = PreferencesUser.create! valid_attributes
      get edit_preferences_user_url(preferences_user)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PreferencesUser" do
        expect {
          post preferences_users_url, params: { preferences_user: valid_attributes }
        }.to change(PreferencesUser, :count).by(1)
      end

      it "redirects to the created preferences_user" do
        post preferences_users_url, params: { preferences_user: valid_attributes }
        expect(response).to redirect_to(preferences_user_url(PreferencesUser.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PreferencesUser" do
        expect {
          post preferences_users_url, params: { preferences_user: invalid_attributes }
        }.to change(PreferencesUser, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post preferences_users_url, params: { preferences_user: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested preferences_user" do
        preferences_user = PreferencesUser.create! valid_attributes
        patch preferences_user_url(preferences_user), params: { preferences_user: new_attributes }
        preferences_user.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the preferences_user" do
        preferences_user = PreferencesUser.create! valid_attributes
        patch preferences_user_url(preferences_user), params: { preferences_user: new_attributes }
        preferences_user.reload
        expect(response).to redirect_to(preferences_user_url(preferences_user))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        preferences_user = PreferencesUser.create! valid_attributes
        patch preferences_user_url(preferences_user), params: { preferences_user: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested preferences_user" do
      preferences_user = PreferencesUser.create! valid_attributes
      expect {
        delete preferences_user_url(preferences_user)
      }.to change(PreferencesUser, :count).by(-1)
    end

    it "redirects to the preferences_users list" do
      preferences_user = PreferencesUser.create! valid_attributes
      delete preferences_user_url(preferences_user)
      expect(response).to redirect_to(preferences_users_url)
    end
  end
end
