 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/preferences", type: :request do
  # Preference. As you add validations to Preference, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Preference.create! valid_attributes
      get preferences_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      preference = Preference.create! valid_attributes
      get preference_url(preference)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_preference_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      preference = Preference.create! valid_attributes
      get edit_preference_url(preference)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Preference" do
        expect {
          post preferences_url, params: { preference: valid_attributes }
        }.to change(Preference, :count).by(1)
      end

      it "redirects to the created preference" do
        post preferences_url, params: { preference: valid_attributes }
        expect(response).to redirect_to(preference_url(Preference.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Preference" do
        expect {
          post preferences_url, params: { preference: invalid_attributes }
        }.to change(Preference, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post preferences_url, params: { preference: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested preference" do
        preference = Preference.create! valid_attributes
        patch preference_url(preference), params: { preference: new_attributes }
        preference.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the preference" do
        preference = Preference.create! valid_attributes
        patch preference_url(preference), params: { preference: new_attributes }
        preference.reload
        expect(response).to redirect_to(preference_url(preference))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        preference = Preference.create! valid_attributes
        patch preference_url(preference), params: { preference: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested preference" do
      preference = Preference.create! valid_attributes
      expect {
        delete preference_url(preference)
      }.to change(Preference, :count).by(-1)
    end

    it "redirects to the preferences list" do
      preference = Preference.create! valid_attributes
      delete preference_url(preference)
      expect(response).to redirect_to(preferences_url)
    end
  end
end
